name: OneDrive to Google Drive Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  cloud_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Install Latest Rclone
        run: |
          sudo -v ; curl https://rclone.org/install.sh | sudo bash

      - name: Restore Rclone Config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG_BASE64 }}" | base64 -d > ~/.config/rclone/rclone.conf

      - name: Sync one1 to Google Drive
        run: |
          rclone copy one1:/ gdrive:/ -v --stats 15s --fast-list \
            --exclude "Personal Vault/**" \
            --exclude "rar/ai/d/file/imgofai.zip" \
            --transfers 4 \
            --checkers 8 \
            --retries 5 \
            --low-level-retries 10 \
            --timeout 3m \
            --contimeout 30s

      - name: Sync one2 to Google Drive
        run: |
          rclone copy one2:/ gdrive:/ -v --stats 15s --fast-list --ignore-existing \
            --exclude "Personal Vault/**" \
            --transfers 4 \
            --checkers 8 \
            --retries 5 \
            --low-level-retries 10 \
            --timeout 3m \
            --contimeout 30s
